### PR TITLE
Dynamo_Toolkit: implement convert for NurbsSurface

### LINKED ISSUE #153: Dynamo_Toolkit: Add convert for NurbsSurface
#### Description:

As per title, to enable pull push of them

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #153 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Dynamo_Toolkit/Dynamo_Toolkit-ConvertForNurbsCurve?csf=1&e=wpSaYD

### Changelog

- Add `Convert.ToBHoM(NurbsSurface)`
- Add `Convert.ToDesignScript(NurbsSurface)`

### CODE REVIEW

**Comment by ZiolkowskiJakub** [comment]
Hi @epiagnatelli,

Any chance for test file?

Thanks in advance!

**Comment by ZiolkowskiJakub** [comment]
Got it! Thanks!

[Test Scripts](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Dynamo_Toolkit/Dynamo_Toolkit-ConvertForNurbsCurve?csf=1&e=wpSaYD)

**Comment by epignatelli** [comment]
Ah - I forgot to add it to the pr description, thanks - I'll add now.

**Comment by epignatelli** [comment]
I have done a simple debug to be more specific about the problem.
image

The conversion is working, the issue lies in another part of the code:
`aType == typeof(T) || typeof(T).IsAssignableFrom(aType)` returns false, you can see why from the debug.
image

I check `ToBHoM` for `Point` and it doesn't work as well.
It feels like this toolkit really needs a little bit of attention, or all the efforts we spend in all the other parts of the BHoM are vain.

Pushing a Nurbs from Grasshopper to Dynamo works:
image

**Comment by pawelbaran** [comment]
Conversion seems to be a boomerang issue in case of Dynamo, I was pinged about it a few times in the past months. 100% agree with @epignatelli, this repo needs a solid review.

Coming back to the PR, in this case I assume that my review is not needed - I can confirm that the code builds, the package loads in Dynamo, but @ZiolkowskiJakub's test fails. Happy to click _Approve_ if needed, assuming that the issue will be investigated further after the 2.3 release.

**Comment by epignatelli** [comment]
Hi guys, I fixed also the other issue.
@alelom is going to create the installer this afternoon, the plan is to get everything read within 2 pm.

Would you mind repeating the test? Let me know the time is too tight!

**Comment by ZiolkowskiJakub** [comment]
Hi All,

> aType == typeof(T) || typeof(T).IsAssignableFrom(aType) returns false, you can see why from the debug.

I had similar issue couple times in Revit_Toolkit and could not find the reason for that. My workaround was to use following method:

```
        [Description("Checks if one type is assignable from another type by comparing its full name.")]
        [Input("typeToCheck", "Type to be checked")]
        [Input("type", "Type")]
        [Output("IsAssignableFromByFullName")]
        public static bool IsAssignableFromByFullName(this Type typeToCheck, Type type)
        {
            if (type == null || typeToCheck == null)
                return false;

            return FullNames(typeToCheck).Contains(type.FullName);
        }

        [Description("Gets full names for given Type.")]
        [Input("type", "Type")]
        [Output("FullNames")]
        private static List<string> FullNames(Type type)
        {
            List<string> aResult = new List<string>();
            aResult.Add(type.FullName);
            if (type.BaseType != null)
                aResult.AddRange(FullNames(type.BaseType));
            return aResult;
        }
```

Not beautiful and quite slow but does the job

**Comment by epignatelli** [comment]
> Hi All,
> 
> > aType == typeof(T) || typeof(T).IsAssignableFrom(aType) returns false, you can see why from the debug.
> 
> I had similar issue couple times in Revit_Toolkit and could not find the reason for that. My workaround was to use following method:
> 
> ```
>         [Description("Checks if one type is assignable from another type by comparing its full name.")]
>         [Input("typeToCheck", "Type to be checked")]
>         [Input("type", "Type")]
>         [Output("IsAssignableFromByFullName")]
>         public static bool IsAssignableFromByFullName(this Type typeToCheck, Type type)
>         {
>             if (type == null || typeToCheck == null)
>                 return false;
> 
>             return FullNames(typeToCheck).Contains(type.FullName);
>         }
> 
>         [Description("Gets full names for given Type.")]
>         [Input("type", "Type")]
>         [Output("FullNames")]
>         private static List<string> FullNames(Type type)
>         {
>             List<string> aResult = new List<string>();
>             aResult.Add(type.FullName);
>             if (type.BaseType != null)
>                 aResult.AddRange(FullNames(type.BaseType));
>             return aResult;
>         }
> ```
> 
> Not beautiful and quite slow but does the job

Thanks @ZiolkowskiJakub ! I pushed a different fix above, aligning with what I do in GH - that should do its job.

**Comment by rwemay** [comment]
Additional test scripts added to the folder above, with sockets in to pass between GH/DYN. The nurbs surface should look like the one in GH. @ZiolkowskiJakub , @epignatelli  FYI

nurbs

**Pull request merged**
