### PR TITLE
Refactoring of Dynamo Toolkit to better leverage the new version of BHoM_UI

### LINKED ISSUE #140: Dynamo_Toolkit: Dynamo Sandbox does not close in process
After running script  and closing dynamo still is open as process in TaskManager

image

### LINKED ISSUE #146: Dynamo_Toolkit: global menu does not work in DynamoRevit
But only in the DynamoSandbox version

### LINKED ISSUE #162: Adjust post-build events to copy just the UI specific files over
#### Broken rules:

This issue is to be solved in unison with https://github.com/BHoM/Dynamo_Toolkit/issues/135
As long as Dynamo will still be using its own folder, compliance will not be guaranteed.

The BHoM_UI is responsible to copy the bhom assemblies to the relative assembly folder.
When Dynamo will comply to store the assemblies into the `BHoM/Assemblies` folder, we need to make sure that it is just copying the minimum necessary files over, i.e. only dynamo-specific files.
See https://github.com/BHoM/BHoM_UI/issues/103 for a bigger picture.

#### Suggestions to restore compliance:

Dynamo should copy just the files relevant to Dynamo.

### LINKED ISSUE #194: Dynamo 1.3: wire gets clicked into first input after clicking minus on the component
#### Description:

Following discussion in #192:

InputBug

The wires should not be clicked into the 1st input on minus hit - they should disappear (opposite to GH, Dynamo does not allow more than one input wire on a single input).

Additionally, what gets left after deleting the component:
image

### LINKED ISSUE #207: Dynamo_Toolkit does not work on Dynamo 2.3 under Revit 2020.2
#### Description:

As in the title: in Dynamo 2.3 on Revit 2020.2 empty BHoM method components do not change after picking the exact method, followed by the UI going crazy:

DynamoBug

Older versions of Revit and Dynamo seem to be not affected.

### LINKED ISSUE #226: Ctrl + Shift + B in Dynamo Interface
#### Description:
Ctrl+Shift+B not functional within Dynamo interface, that or intellisense capability will help users to find commands more easily

### LINKED ISSUE #239: Modify DynamoSettings.xml at build to point to ProgramData/BHoM
#### Description:
Follow up on https://github.com/BHoM/Dynamo_Toolkit/pull/238.

To avoid having to copy all dlls to `Roaming/Dynamo` we can instead make sure that `DynamoSettings.xml` contains a reference to `ProgramData/BHoM`.

### LINKED ISSUE #241: Dynamo_Toolkit: Outputs of Explode do not get updated after input is changed
#### Description:

Please see the .gif. What is more, there is no Update Outputs context button (not sure if that is on purpose, in GH there is one).

RevitAdapter

### LINKED ISSUE #243: Dynamo_Toolkit: Explode of CustomObjects always returns default property names
#### Description:

Regardless the name of a property set to `CustomObject`, it will always be exploded as item1, item2 etc. as in the .gif:

RevitAdapter

### LINKED ISSUE #249: Dynamo_Toolkit: shall we stop supporting Dynamo 1.3?
A few facts:
- Dynamo 2.0 is compatible with Revit since version 2017 and obligatory from 2020
- BHoM for Dynamo has not been updated for quite some time and contains a multitude of bugs
- we are aiming to migrate the assemblies to the central folder (https://github.com/BHoM/Dynamo_Toolkit/pull/240)

Facing all that, would it not be reasonable to shake off some burden and simply exclude Dynamo 1.3 from any future development, i.e. remove the projects, and exclude Dynamo 1.3 from the installer?

### LINKED ISSUE #256: Add call to usage log
#### Description:
Same as already done in Grasshopper. The method from BHoM_UI is `LogUsage`

### LINKED ISSUE #261: Dynamo_Toolkit: Components with missing obligatory inputs do not raise that fact
#### Description:

In GH the component with missing inputs is orange and does not return anything, while in Dynamo it is standard grey with no warning, therefore very easy to pass a `null` that breaks everything downstream. I would consider changing the behaviour to an exception (the component turning yellow).

image

### LINKED ISSUE #264: Dynamo_Toolkit: +/- seems not to work on constructor-based Create components
#### Description:

Please see the animation below:

Dynamo

### LINKED ISSUE #265: Refactoring of Dynamo to better leverage BHoM_UI

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #265 

This is a similar exercise than the one done for Excel and Grasshopper.

I will add any additional issues fixed by this PR as I go along

Closes #140
Closes #146
Closes #162 
Closes #194 
Closes #207 
Closes #226 
Closes #239 
Closes #241
Closes #243
Closes #249 
Closes #261
Closes #264

### Additional comments
- Note, that some components like `Create.Point` are failing for me on Revit 2019 only. Some native component are failing too. After looking further into this, I realised that this was happening even without the BHoM installed so not sure what is causing it. See issue #266 
- The centralisation of the dlls is only done for 2.3 as it seems that feature is not well supported in 2.0

### CODE REVIEW

**Comment by pawelbaran** [comment]
@adecler could you please let us know when ready for review? Can't wait! 🍾

**Comment by adecler** [comment]
@pawelbaran, I suggest you switch to this branch already to provide a continuous review.
The plan is to have this PR ready by the end of the first sprint but I will keep it in a state that is always usable as is.

**Comment by pawelbaran** [comment]
I have just tried a build on today's Alpha combined with this branch. Dynamo 2.3 (Revit 2020) crashes when I open a new Dynamo file. I get the following exception:

image

image

A breakpoint on `GlobalSearchMenu.Activate` does not get hit at all. 

@adecler do you have any idea what can go wrong here?

**Comment by adecler** [comment]
It might be related to the fact that we migrated to 4.0 ?
I can see that your error is still referencing 3.0 so something is wrong there. Can you make sure your local copy of the branch is up to date ?

This is what you should have on the Dynamo Roaming folder:

image

**Comment by pawelbaran** [comment]
Reinstall of the latest Alpha + rebuild fixed the issue. I will keep on testing, thanks!

**Comment by adecler** [comment]
**Warning**: If you update your code using an installer, make sure to delete teh content of those two fodlers manually:
- C:\Users\adecler\AppData\Roaming\Dynamo\Dynamo Core\2.3\packages\BHoM\bin
- C:\Users\adecler\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\BHoM\bin

The reason for that is because this PR is now using the ProgramData folder to find its BHoM dlls. Since the installer still copies all dlls in the folders above, you might end up with dlls of different versions being loaded. Resulting in really weird bugs.

**Comment by adecler** [comment]
I had to make a change in BHoM_UI for the ParamSelector menu to stay in sync after clicking on the `-` buttons on the component. 

You can find the PR here: https://github.com/BHoM/BHoM_UI/issues/320

There is no direct dependency so PRs can be merged independently but good to switch to that one too when you are doing the testing.

**Comment by adecler** [comment]
I believe this PR is now ready for review. I did some initial testing following the testing procedure for Dynamo and all seems to working ok. No doubt we will find plenty of bugs once stress tested more heavily though :smile:.

Personally, I have found two problems so far:
- _Explode warning messages don't go away when the outputs have changed_. That's a weird one. it's linked to Dynamo really unhappy when you change its output parameters. I looked into it but not sure how to fix it tbh. Notice that copy/pasting the Explode component remove the warning so there is probably a way to get the warning message without having to do that.
- _No way to force list on object input (e.g. Custom Object)_. That would be the equivalent of selecting `List` in the input contextual menu in Grasshopper. Maybe there is already a ways to do that in Dynamo but I couldn't figure this out. The best solution would probably be to leverage the new dialog window for editing the input name by adding a toggle for list as well.

Also be aware that I have removed the menu to select outputs as there are too many bugs on the Dynamo side for it to be worth it. I managed to get the input selection working though

**Comment by pawelbaran** [comment]
In general LGTM, well done @adecler! I've found 2 issues that would it be nice to cover before merging:

1. For some reason I am not able to `Explode` nor query the `Location` of a pulled wall - please see the _PullWall.rvt_ and _PullWall.dyn_ files [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue255%2DUIRefactoring&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
2. Actually the second point you've mentioned in your comment: forcing list input is possible by managing input levels, which can be switched on by clicking on the arrow as in the screenshot and ticking _Use Levels_ option:
image
From what I have tested, the input levels are managed differently for BHoM and Dynamo (please see _ListManagement.dyn_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue255%2DUIRefactoring&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)). Based on my experience, the approach used by Dynamo is quite hard to capture (particularly for the ones grown up on GH trees), but in this case I think it would be fair to say that BHoM should simply mimic the way in which Dynamo handles the inputs (or even better, make Dynamo do that). As an extra reference, you could have a look at [the relevant chapter of Dynamo Primer](https://primer.dynamobim.org/06_Designing-with-Lists/6-3_lists-of-lists.html), particularly the _List@Level_ paragraph.

It would be great to cover the above in this PR, but I would also be ready to approve as is and resolve the missing bits in the follow-up threads.

**Comment by kayleighhoude** [comment]
@adecler looking good so far. One thing I noticed, when using the global menu it works for adapters, engine methods, types but does not work specifically for datasets. I've tried this with multiple datasets. Not sure if this occurred for you too @pawelbaran 
DatasetsGlobalMenu

**Comment by adecler** [comment]
Thanks @pawelbaran , 

I have fixed the issue you found with Explode. Actually it was linked to output setters not covering for Exceptional cases like conversion th DesignScript failing or handling of nulls. That's probably a point worth mentioning: there is no easy way to keep the object as BHoM when outputting them and only converting when requested as input (like in Grasshopper). This means that we always convert to Design script so a lot more susceptible to conversions errors. 

As for your second point, it looks like it will require a bit more time than I can afford this sprint. I have raised a spearate issue for that here: https://github.com/BHoM/Dynamo_Toolkit/issues/271

**Comment by adecler** [comment]
Thanks @kayleighhoude , this should now be fixed.

**Comment by pawelbaran** [comment]
I ran another round of tests trying to break the thing. It was not easy, well done 👍 

Concerning the 1st point of my previous review, `Explode` and `GetProperty` works now, but they still turn yellow + the output geometry does not cast to DesignScript (i.e. it is useless for a regular user who does not know anything about BHoM vs DesignScript casting). Not sure if anything could be done about it, taken into account your previous comment, but would be great to fix that or at least leave an informative error if possible.

**Comment by adecler** [comment]
@pawelbaran, the error message is as follows:
```
Engine.Reflection.Compute.RecordWarning("Failed to convert output " + index + " to DesignScript. Returning it without conversion.\nError: " + e.Message);
```

I am happy to change it to whatever you feel is more appropriate.

Keep in mind that error/behaviour is only happening if the conversion methods are failing to create a valid DesignScript object. So the best way to improve this is to improve the conversion methods themselves. That is very much outside my confort zone as I have never used those objects myself. So this approach is to make sure I at least return something more useful than a null (or even worst in the previous case, cause all the outputs to fail). 
-

**Comment by pawelbaran** [comment]
Good point @adecler, I assumed the error comes from the UI, not the Engine, apologies. The error comes from the line below, which should also contain a null check for `InternalBoundaries`:

https://github.com/BHoM/Dynamo_Toolkit/blob/d202ceedee5e4ee4198f7acfb09c364e38888191/Dynamo20/Dynamo_Engine/Convert/ToDesignScript.cs#L232

The above should be:
```
if (surface.InternalBoundaries != null && surface.InternalBoundaries.Count != 0)
```

I think it could be included by you in this PR, but happy to open a new one after this gets merged - up to you.

**Comment by adecler** [comment]
@pawelbaran ,  I have added basic null checks on all `ToDesignScript` and `FromDesignScript` methods to make you life a bit easier when you review those methods. Feel free to edit as you see fit.

**Review by pawelbaran — APPROVED** [review]
LGTM now, but I would be way more comfortable if we had more than one approving review before merging this PR - the scope of changes is massive, cross-check would be more than welcome.

**Comment by adecler** [comment]
> LGTM now, but I would be way more comfortable if we had more than one approving review before merging this PR - the scope of changes is massive, cross-check would be more than welcome.

Fully agreed. I suppose the most important review to get would be from @kayleighhoude . Kayleigh, would it be possible for you to do another review ?

**Review by kayleighhoude — COMMENTED** [review]
One thing I noticed, when using a specific LCA Scope object I had the following message pop up (this does not occur within the Grasshopper interface):
image
Is this something that can be rectified within this PR @adecler?

**Comment by adecler** [comment]
Thanks @kayleighhoude,

This is now fixed. Thanks to Dynamo requiring us to provide individual methods for each parameter count in order for lacing to work, we had only covered up to 12 parameters. Doing a quick analysis of the BHoM methods, I noticed that we have one method with 35 parameters and one with 27. So I decided to cover up to 40 parameters just to be safe.  Thanks god for Grasshopper to generate that code automatically through scripting !

**Review by kayleighhoude — APPROVED** [review]
Happy to approve this now after ~20 hours of using BHoM in Dynamo this week!

**Pull request merged**
