### PR TITLE
Update IElement references with the Dimensional_oM

### LINKED ISSUE #212: Update IElement references with the Dimensional_oM
`IElement` interfaces are migrating to `Dimensional_oM`

This will cause every project which uses any of the `IElement`s or any class inheriting from `IElement` to need a reference to `Dimensional_oM`. 
Further more, any file using any of the `IElement` interfaces explicitly, will need to add 
`using BH.oM.Dimensional;`

### Branch Name:
`Dimensional_oM698-Migrate-IElementXD-Interfaces-from-Geometry_oM`

##### For every project in your toolkit
1. If you had a reference to Geometry_oM, add a reference to Dimensional_oM

##### For every file in your toolkit
2. If you have any direct use of any of the `IElement` interfaces, add `using BH.oM.Dimensional;`

### PR DESCRIPTION
**Pull request by kThorsager**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193

### Issues addressed by this PR
Closes #212 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
> On a separate note, I a not sure why we need to add those references. It compiles fine without them for me.

I think (if I have understood @kThorsager correctly), the toolkit will depend on them once https://github.com/BHoM/BHoM/pull/704 is merged because the IElement references move from Geometry to Dimensional? I could be wrong though.

I do need to have a chat with @kThorsager today about it as I asked him to add `do-not-merge` labels to everything but it might be that some of them can be merged in advance (providing the changes are accepted of course) :smile:

**Comment by adecler** [comment]
> I think (if I have understood @kThorsager correctly), the toolkit will depend on them once BHoM/BHoM#704 is merged because the IElement references move from Geometry to Dimensional? I could be wrong though.

That's probably correct. I have to admit, I didn't migrate all the necessary repos to test properly yet. But noticed that oM.Dimensional was not used anywhere (I mean I was expecting this PR to add some `using oM.Dimnesional` but it doesn't).

**Comment by al-fisher** [comment]
Thanks @adecler @FraserGreenroyd - on comments above - I must admit peeping from afar, I was surprised to see quite so many PRs and simple references to `Dimensional_oM` needed across toolkits. Similar to you @adecler, is likely because I have not tracked through fully (in my head at least). And I will have a proper review before Monday’s scheduled merge party - but will be great if you too could both also confirm happy with strategy and required references needed here. Cheers both 🙏 

Thanks @kThorsager for pushing this and getting all through! 👍 Such a good foundational one to bottom out! Well done! Worth taking @adecler & @FraserGreenroyd through the logic - and making a note - ready for a smooth process on Monday! 😄 Thanks!

**Comment by kThorsager** [comment]
Yes, I too was surprised at the amount of toolkits needing references, but my first step of every PR was to build without changes and observe the errors, which there was. 

This seems to be because if say a `Line` is used as say a `ICurve`, the compiler needs to know all of the inherited classes and interfaces, and upon facing `IElement` it is unhappy.

This also leads to special cases such as BHoM_UI which is using `Point`, but only ever as a `Point` and is hence not affected.

Hope this clarifies

**Pull request merged**
