### PR TITLE
Expose both Dynamo 1.3 and 2.0 on master

### LINKED ISSUE #202: Expose projects for both Dynamo 1.3 and 2.0
Instead of keeping them as separated branches, have both version available on the master

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #202 

After the comment from @pawelbaran ([here](https://github.com/BHoM/Dynamo_Toolkit/pull/197#issuecomment-579794894)) regarding moving 1.3 to a separate branch, I had second thoughts about it and decided to give a shot to exposing both Dynamo 1.3 and 2.0 on the master. Here's the result of that.

image

It is important to note that we don't have the resources to maintain the BHoM UI for both 1.3 and 2.0 so 1.3 will still not be supported anymore. This option makes this less clear but it is fair to admit that it brings its benefits too. 

Only the file structure are changed here, not the files themselves. So don't be scared by the file changes shown here.

Notice I labelled this with a `question` because that was not what had been agreed before. This is you chance to give your opinion. Speak now or forever hold your peace.

### Additional comments
- You will notice that each version is inside its own separate folder (inside Dynamo_Toolkit obviously). That includes a separate build folder. As opposed to the adapters where we want all versions to be exposed at the same time, we want to keep a clear separation in this case. 
- With the projects being one level deeper in the folder structure, the build folders are note being picked anymore by PostBuild. A nice side-effect if I am honest. 
- It also means that there might be a bit of work on the CI side for the cases where Dynamo is being checked. @FraserGreenroyd , can you look into that?

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
The nature of this PR means that @BHoMBot is unable to update the copyright headers for this toolkit at this stage to avoid too many conflicts or double handling of files/extra work.

As such, with discussion with @al-fisher , when this PR is merged we will then instruct @BHoMBot to update the copyright headers. Whoever merges this PR, could you be so kind as to alert myself and @al-fisher directly so we can action the @BHoMBot actions.

As for the other CI stuff, I will look into that ASAP @adecler :smile:

**Comment by al-fisher** [comment]
Thanks @pawelbaran @adecler 
Yep - as discussed @adecler - agree with this as an approach. Even as primary focus of development switches to later versions good to have older running in parallel. 
Also discussed documenting notes on readmes more clearly now about versions supported/implemented/testing on CI etc. for each adapter/software UI 
This links to chat about adapter documentation and matrix of implemented functionality @alelom

**Comment by FraserGreenroyd** [comment]
I've had a look at the CI element of this, and because the projects are all in the same `sln` file without separate build configurations, there is no issue with CI. CI will attempt to compile Dynamo13 and Dynamo20 on every CI check.

I am therefore happy with the set up of this from the CI point of view.

**Comment by adecler** [comment]
Thanks @FraserGreenroyd !

Then I guess it's down to at least one of you to do a final review and approve 😄 .

**Comment by adecler** [comment]
Anyone wants to volunteer to do a final review ?

**Comment by pawelbaran** [comment]
I will give it a shot functionality wise on Monday @adecler

**Comment by pawelbaran** [comment]
@adecler not sure if this is a subject of this PR, but in Dynamo 2.3 under Revit 2020.2 I get a weird behaviour - empty BHoM method components do not change after picking the exact method, followed by the UI going nuts:

DynamoBug
 
On Dynamo 2.0.2 under Revit 2018.3 as well as Dynamo 1.3.4 under Revit 2019.2 everything works nicely.

The reason for issues with Revit 2020 might be that since this version Dynamo is built into Revit (which you probably know) - of course it is done as bad as anything else related to Dynamo, so problems can strike out of the blue, and only on some machines.

Another thing I noticed is that in `AppData` I have 5 Dynamo subfolders (1.3, 2.0, 2.1, 2.2, 2.3) with BHoM libraries being copied only to 1.3, 2.0 and 2.3. Is this done on purpose (knowing somehow that these are the only versions used by Revit on my machine atm) or is it a coincidence? If the latter, then a postbuild needs some tweaks I guess.

Finally, I am happy to approve this PR if you prefer the above in separate issues.

**Comment by adecler** [comment]
Thanks @pawelbaran .

This is very strange indeed. I had a quick look but couldn't really figure out what was causing the problem as everything looks fine on the side of the code (input ports added successfully to the node, etc) so it will need to be investigated further. The only version that demonstrate that bug is Dynamo 2.3 on Revit 2020. Dynamo 2.3 Sandbox work perfectly fine (which is annoying since this is usually what I use to debug as I have the source code). As this PR is adding back 1.3 without touching 2.3, I would suggest merging it and raising separate issues (please mark the bug issues as critical).

I personally only have 1.3, 2.0 and 2.3 sub-folders on AppData. I was not aware of a need for 2.1 and 2.2 but happy to add them if they are necessary. Can you raise an issue for that if you think so?

**Pull request merged**
