### PR TITLE
Expose both Dynamo 1.3 and 2.0 on master

### LINKED ISSUE #202: Expose projects for both Dynamo 1.3 and 2.0
Instead of keeping them as separated branches, have both version available on the master

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR

Closes #202 

After the comment from @pawelbaran ([here](https://github.com/BHoM/Dynamo_Toolkit/pull/197#issuecomment-579794894)) regarding moving 1.3 to a separate branch, I had second thoughts about it and decided to give a shot to exposing both Dynamo 1.3 and 2.0 on the master. Here's the result of that.

image

It is important to note that we don't have the resources to maintain the BHoM UI for both 1.3 and 2.0 so 1.3 will still not be supported anymore. This option makes this less clear but it is fair to admit that it brings its benefits too. 

Only the file structure are changed here, not the files themselves. So don't be scared by the file changes shown here.

Notice I labelled this with a `question` because that was not what had been agreed before. This is you chance to give your opinion. Speak now or forever hold your peace.

### Additional comments
- You will notice that each version is inside its own separate folder (inside Dynamo_Toolkit obviously). That includes a separate build folder. As opposed to the adapters where we want all versions to be exposed at the same time, we want to keep a clear separation in this case. 
- With the projects being one level deeper in the folder structure, the build folders are note being picked anymore by PostBuild. A nice side-effect if I am honest. 
- It also means that there might be a bit of work on the CI side for the cases where Dynamo is being checked. @FraserGreenroyd , can you look into that?

The above is the original PR commentary from @adecler .

Following merge of the original PR, it was found that the installer could not build. This was not found in the original CI check on the PR.

This PR is being raised again, following the revert PR earlier to allow this to be considered again, but with a fresh focus on the installer itself and the implications on that. FYI: @awakeman this may need some work from you to assist.

Please test this PR again using your standard scripts, but please do not merge until the following checks pass:

 - CheckCore
 - CheckInstaller

To highlight the issue, I am running CheckInstaller as soon as I raise this PR, which will return a failure result. Until that goes to pass, this PR should not be merged.

### CODE REVIEW

**Comment by adecler** [comment]
To keep record of my response via email:

> First thing that comes to mind is the same as what I said when creating the Dynamo PR: the folder structure is different than usual with the build folder being separated for 1.3 and 2.0. So I would not be surprised if the default installer is not picking them up.

**Comment by FraserGreenroyd** [comment]
> Most of the BHoM references have CopyLocal set to true. Happy to push a change to correct that.

That'd be great if you could @awakeman - thanks :smile:

**Comment by FraserGreenroyd** [comment]
Proposed events to enable this to move forward, @adecler and @awakeman to confirm if happy. To be completed by myself and @awakeman if agreement is in place.

 - Merge this PR after Sprint Kick Off Tuesday AM (UK time)
 - Re-run Installer PR check
 - Test installer artefact
 - If good, merge installer
 - Check CI checks on installers on an open PR somewhere (BHoM_Engine has a few)

**Pull request merged**
