### PR TITLE
Log file id and file path

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2312
https://github.com/BHoM/BHoM_UI/pull/370

   
### Issues addressed by this PR
Provide changes required for fileName and project code to be saved by analytics.

### Test files
Will be tested alongside the [BHoMAnalytics PR](https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/16)

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by AndreBalasian** [comment]
Is it possible to log usage by Dynamo scripts that don't contain any BHoM functionality, perhaps by calling some method?
If so, could you recommend a method that doesn't do much, but could be placed in a script for the sake of logging the use of that script file?

**Comment by adecler** [comment]
> Is it possible to log usage by Dynamo scripts that don't contain any BHoM functionality, perhaps by calling some method?
If so, could you recommend a method that doesn't do much, but could be placed in a script for the sake of logging the use of that script file?

@AndreBalasian , The new SetProjectID component from this set of PRs seems to be a good candidate for that. See https://github.com/BHoM/BHoM_UI/pull/370

**Comment by pawelbaran** [comment]
I have just tested the PR, looks like it works fine locally (`SetProjectID` checked, local log creation checked, local log update checked). Could you check if the logs got recorded in the database too, @adecler @al-fisher? ProjectIds are _Hey Jude 18_ for Revit 2018 + Dynamo 2.0 and _Hey Jude 20_ for Revit 2020 and Dynamo 2.3 🙈

**Comment by adecler** [comment]
> Could you check if the logs got recorded in the database too, @adecler @al-fisher? ProjectIds are Hey Jude 18 for Revit 2018 + Dynamo 2.0 and Hey Jude 20 for Revit 2020 and Dynamo 2.3 🙈

Yes, they are showing in the database. Thanks @pawelbaran

**Review by pawelbaran — APPROVED** [review]
Approving then, the code LGTM 👍

**Pull request merged**
