### PR TITLE
Fix Dynamo crash on intitialisation of GlobalSearchMenu type

### LINKED ISSUE #280: Dynamo 2.3.0.5885 crashing with BHoM 4.0.alpha (Revit 2020)
#### Description:
When i'm trying to run Dynamo 2.3.0.5885 in Revit 2020, at the first try there is dynamo crash.
image
Second try kills whole Revit

More info:
image
image

after uninstalling:
image

#### Steps to reproduce:
Install BHoM daily update
Run Revit 2020
Run dynamo (it's ok), new script (crash)

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #280

This is the only thing that I can think of that would cause the crash mentioned in issue #280. Since I cannot reproduce the bug myself, this is only a guess. If that doesn't work, someone with the bug will have to run Dynamo with VS attached.

@mikolaj-nazarczuk

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check copyright

**Review by mikolaj-nazarczuk — APPROVED** [review]
These changes fixed a bug that was causing Dynamo crash.

**Comment by pawelbaran** [comment]
@BHoMBot check copyright

**Pull request merged**
