### PR TITLE
UI Refactoring

### LINKED ISSUE #256: Add call to usage log
#### Description:
Same as already done in Grasshopper. The method from BHoM_UI is `LogUsage`

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/297

   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM_UI/pull/297 for details

Right now, only minor changes to keep things working have been done. Sprint 3 will focus on leveraging the changes on BHoM_UI.

Fixes #256

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Did some first really quick testing. Some issues found.

#### Dynamo 1.3

Tried simply pulling some bars from Robot, exploding them and exploding the start node. Pulling worked, exploding the bars worked, exploding the start nodes did _not_ work. Component complained about outputs not matching outputs straight after plugged in:

image


#### Dynamo 2.0

Tried setting up the same script in dynamo for revit 2020 (version 2.X)

I did start by adding a random native component to the canvas before doing any BHoMRelated things.

1. Ctrl+shift+b menu does not work (think this was here before as well)
2. Tried creating the same script as I did for 3.0. Dynamo crashed out when trying to select structural Bar from the CreateType component

**Comment by pawelbaran** [comment]
Today we made a functionality review together with @adecler, in general everything works fine, 2 major bugs found:
- all inputs and outputs of _Create_ component get duplicated once the script is saved and reopened - test file _CreateComponent.dyn_ available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue255%2DUIRefactoring&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- _CreateType_ component is crashing Dynamo immediately when the user chooses a type

All tests were run on Dynamo 2.X because as discussed in https://github.com/BHoM/Dynamo_Toolkit/issues/249, 1.3 is meant not to be supported any more.

**Comment by adecler** [comment]
@pawelbaran , both bugs are now fixed (one was fixed in BHoM_UI).
Can you confirm you are happy with the changes ?

**Comment by pawelbaran** [comment]
Everything seems to work fine, happy! 👍

**Pull request merged**
